#!/usr/bin/env bash

if [[ -z $BASE16_SHELL_THEME_NAME_PATH ]]; then
  BASE16_SHELL_THEME_NAME_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/tinted-theming/theme_name" 
fi

# If $BASE16_SHELL_THEME_NAME_PATH exists extract the file contents
read current_theme_name_from_config_file < "$BASE16_SHELL_THEME_NAME_PATH"

# Use $current_theme_name_from_config_file else $BASE16_THEME else $BASE16_THEME_DEFAULT else "default-dark"
theme_name="${1:-${current_theme_name_from_config_file:-${BASE16_THEME:-${BASE16_THEME_DEFAULT:-default-dark}}}}"
theme=$(dirname $0)/scripts/base16-${theme_name}.sh
if [ -f $theme ]; then
  # get the color declarations in said theme, assumes there is a block of text that starts with color00= and ends with new line
  source $theme
  eval $(awk '/^color00=/,/^$/ {print}' $theme | sed 's/#.*//')
else
  printf "No theme file %s found\n" $theme
fi;
ansi_mappings=(
  Black
  Red
  Green
  Yellow
  Blue
  Magenta
  Cyan
  White
  Bright_Black
  Bright_Red
  Bright_Green
  Bright_Yellow
  Bright_Blue
  Bright_Magenta
  Bright_Cyan
  Bright_White
)
colors=(
  base00
  base08
  base0B
  base0A
  base0D
  base0E
  base0C
  base05
  base03
  base08
  base0B
  base0A
  base0D
  base0E
  base0C
  base07
  base09
  base0F
  base01
  base02
  base04
  base06
)
for padded_value in `seq -w 0 21`; do
  color_variable="color${padded_value}"
  eval current_color=\$${color_variable}
  current_color=$(echo ${current_color//\//} | tr '[:lower:]' '[:upper:]') # get rid of slashes, and uppercase
  non_padded_value=$((10#$padded_value))
  base16_color_name=${colors[$non_padded_value]}
  current_color_label=${current_color:-unknown}
  ansi_label=${ansi_mappings[$non_padded_value]} 
  block=$(printf "\x1b[48;5;${non_padded_value}m___________________________")
  foreground=$(printf "\x1b[38;5;${non_padded_value}m$color_variable")
  printf "%s %s %s %-30s %s\x1b[0m\n" $foreground $base16_color_name $current_color_label ${ansi_label:-""} $block
done;
if [ $# -eq 1 ]; then
    printf "To restore current theme, source $HOME/.config/tinted-theming/base16_theme or reopen your terminal\n"
fi
