#!/usr/bin/env bash

# ----------------------------------------------------------------------
# Setup config variables and env
# ----------------------------------------------------------------------
#

BASE16_JQP_CONFIG_FILE="${BASE16_JQP_CONFIG_FILE:-$BASE16_CONFIG_PATH/jqp_theme.yaml}"

if [ ! -e "$BASE16_JQP_CONFIG_FILE" ]; then
  touch "$BASE16_JQP_CONFIG_FILE"
fi

read -r current_theme_name < "$BASE16_SHELL_THEME_NAME_PATH"

# ----------------------------------------------------------------------
# Execution
# ----------------------------------------------------------------------
#
cat <<EOF >! $BASE16_JQP_CONFIG_FILE
# vim: ft=yaml
# DO NOT EDIT! Generated by tinted-shell.
# Base16 Theme: ${current_theme_name}
theme:
  name: "native"
  chromaStyleOverrides:
    bg: "noinherit #${BASE16_COLOR_05_HEX} bg:#${BASE16_COLOR_00_HEX}"
    kc: "noinherit #${BASE16_COLOR_0E_HEX}"
    p: "noinherit #${BASE16_COLOR_05_HEX}"
    "": "noinherit #${BASE16_COLOR_05_HEX}"
    c: "noinherit #${BASE16_COLOR_03_HEX}"
    ch: "noinherit #${BASE16_COLOR_03_HEX}"
    cm: "noinherit #${BASE16_COLOR_03_HEX}"
    cp: "noinherit #${BASE16_COLOR_03_HEX}"
    cs: "noinherit #${BASE16_COLOR_03_HEX}"
    m: "noinherit #${BASE16_COLOR_09_HEX}"
    mb: "noinherit #${BASE16_COLOR_09_HEX}"
    mf: "noinherit #${BASE16_COLOR_09_HEX}"
    mh: "noinherit #${BASE16_COLOR_09_HEX}"
    mi: "noinherit #${BASE16_COLOR_09_HEX}"
    il: "noinherit #${BASE16_COLOR_09_HEX}"
    mo: "noinherit #${BASE16_COLOR_09_HEX}"
    s: "noinherit #${BASE16_COLOR_0B_HEX}"
    sa: "noinherit #${BASE16_COLOR_0B_HEX}"
    sb: "noinherit #${BASE16_COLOR_0B_HEX}"
    sc: "noinherit #${BASE16_COLOR_0B_HEX}"
    dl: "noinherit #${BASE16_COLOR_0F_HEX}"
    sd: "noinherit #${BASE16_COLOR_0B_HEX}"
    s2: "noinherit #${BASE16_COLOR_0B_HEX}"
    se: "noinherit #${BASE16_COLOR_0C_HEX}"
    sh: "noinherit #${BASE16_COLOR_0B_HEX}"
    si: "noinherit #${BASE16_COLOR_0C_HEX}"
    sx: "noinherit #${BASE16_COLOR_0B_HEX}"
    sr: "noinherit #${BASE16_COLOR_0C_HEX}"
    s1: "noinherit #${BASE16_COLOR_0B_HEX}"
    ss: "noinherit #${BASE16_COLOR_0B_HEX}"
    nt: "noinherit #${BASE16_COLOR_0B_HEX}"
EOF

unset jqp_config_output
unset current_theme_name
